import skin from "../../assets/icons/skin.svg";
import size from "../../assets/icons/size.svg";
import hair from "../../assets/icons/hair.svg";
import hairColor from "../../assets/icons/hairColor.svg";
import smile from "../../assets/icons/smile.svg";
import face from "../../assets/icons/face.svg";
import makeup from "../../assets/icons/makeUp.svg";
import glasses from "../../assets/icons/glasses.svg";
import crop from "../../assets/icons/crop.svg";
import background from "../../assets/icons/background.svg";
import blur from "../../assets/icons/blur.svg";

import filter from "../../assets/filter.jpg";

export const ButtonsFace = [
  { key: "skin", name: "Кожа", src: skin },
  { key: "size", name: "Размеры", src: size },
  { key: "hair", name: "Прически", src: hair },
  { key: "hairColor", name: "Цвет волос", src: hairColor },
  { key: "smile", name: "Улыбки", src: smile },
  { key: "face", name: "Черты", src: face },
  { key: "makeup", name: "Макияж", src: makeup },
  { key: "glasses", name: "Очки", src: glasses },
];

export const ButtonsInstruments = [
  { key: "crop", name: "Обрезать", src: crop },
  { key: "background", name: "Фоны", src: background },
  { key: "blur", name: "Размытие", src: blur },
];

export const subFilters = {
  hair: [
    {
      id: 0,
      name: "Оригинал",
      img: filter,
      hair_style: "Original",
      numFilters: 0,
    },
    {
      id: 1,
      name: "Ёжик",
      img: filter,
      hair_style: "BuzzCut",
      numFilters: 0,
    },
    {
      id: 2,
      name: "Андеркат",
      img: filter,
      hair_style: "UnderCut",
      numFilters: 0,
    },
    {
      id: 3,
      name: "Помпадур",
      img: filter,
      hair_style: "Pompadour",
      numFilters: 0,
    },
    {
      id: 4,
      name: "Зачёс назад",
      img: filter,
      hair_style: "SlickBack",
      numFilters: 0,
    },
    {
      id: 5,
      name: "Кудрявый",
      img: filter,
      hair_style: "CurlyShag",
      numFilters: 0,
    },
    {
      id: 6,
      name: "Волнистый",
      img: filter,
      hair_style: "WavyShag",
      numFilters: 0,
    },
    {
      id: 7,
      name: "Фальш-хоук",
      img: filter,
      hair_style: "FauxHawk",
      numFilters: 0,
    },
    {
      id: 8,
      name: "Торчащий",
      img: filter,
      hair_style: "Spiky",
      numFilters: 0,
    },
    {
      id: 9,
      name: "Пробор",
      img: filter,
      hair_style: "CombOver",
      numFilters: 0,
    },
    {
      id: 10,
      name: "Фейд",
      img: filter,
      hair_style: "HighTightFade",
      numFilters: 0,
    },
    {
      id: 11,
      name: "Пучок",
      img: filter,
      hair_style: "ManBun",
      numFilters: 0,
    },
    { id: 12, name: "Афро", img: filter, hair_style: "Afro", numFilters: 0 },
    {
      id: 13,
      name: "Низкий фейд",
      img: filter,
      hair_style: "LowFade",
      numFilters: 0,
    },
    {
      id: 14,
      name: "Длинный андеркат",
      img: filter,
      hair_style: "UndercutLongHair",
      numFilters: 0,
    },
    {
      id: 15,
      name: "Два блока",
      img: filter,
      hair_style: "TwoBlockHaircut",
      numFilters: 0,
    },
    {
      id: 16,
      name: "Френч",
      img: filter,
      hair_style: "TexturedFringe",
      numFilters: 0,
    },
    {
      id: 17,
      name: "Горшок",
      img: filter,
      hair_style: "BluntBowlCut",
      numFilters: 0,
    },
    {
      id: 18,
      name: "Завитки",
      img: filter,
      hair_style: "LongWavyCurtainBangs",
      numFilters: 0,
    },
    {
      id: 19,
      name: "Небрежный",
      img: filter,
      hair_style: "MessyTousled",
      numFilters: 0,
    },
    {
      id: 20,
      name: "Косички",
      img: filter,
      hair_style: "CornrowBraids",
      numFilters: 0,
    },
    {
      id: 21,
      name: "Хвост",
      img: filter,
      hair_style: "LongHairTiedUp",
      numFilters: 0,
    },
    {
      id: 22,
      name: "Пробор по центру",
      img: filter,
      hair_style: "Middle-parted",
      numFilters: 0,
    },

    {
      id: 23,
      name: "Пикси с выбритыми",
      img: filter,
      hair_style: "ShortPixieWithShavedSides",
      numFilters: 0,
    },
    {
      id: 24,
      name: "Аккуратный боб",
      img: filter,
      hair_style: "ShortNeatBob",
      numFilters: 0,
    },
    {
      id: 25,
      name: "Два пучка",
      img: filter,
      hair_style: "DoubleBun",
      numFilters: 0,
    },
    {
      id: 26,
      name: "Укладка",
      img: filter,
      hair_style: "Updo",
      numFilters: 0,
    },
    {
      id: 27,
      name: "Пикси-ирокез",
      img: filter,
      hair_style: "Spiked",
      numFilters: 0,
    },
    {
      id: 28,
      name: "Горшок",
      img: filter,
      hair_style: "bowlCut",
      numFilters: 0,
    },
    {
      id: 29,
      name: "Шиньон",
      img: filter,
      hair_style: "Chignon",
      numFilters: 0,
    },
    {
      id: 30,
      name: "Пикси",
      img: filter,
      hair_style: "PixieCut",
      numFilters: 0,
    },
    {
      id: 31,
      name: "Назад",
      img: filter,
      hair_style: "SlickedBack",
      numFilters: 0,
    },
    {
      id: 32,
      name: "Длинные кудри",
      img: filter,
      hair_style: "LongCurly",
      numFilters: 0,
    },
    {
      id: 33,
      name: "Кудрявый боб",
      img: filter,
      hair_style: "CurlyBob",
      numFilters: 0,
    },
    {
      id: 34,
      name: "Короткий боб с кудрями",
      img: filter,
      hair_style: "StackedCurlsInShortBob",
      numFilters: 0,
    },
    {
      id: 35,
      name: "Пробор с фейдом",
      img: filter,
      hair_style: "SidePartCombOverHairstyleWithHighFade",
      numFilters: 0,
    },
    {
      id: 36,
      name: "Боб 1920-х",
      img: filter,
      hair_style: "WavyFrenchBobVibesfrom1920",
      numFilters: 0,
    },
    { id: 37, name: "Боб", img: filter, hair_style: "BobCut", numFilters: 0 },
    {
      id: 38,
      name: "Короткие хвостики",
      img: filter,
      hair_style: "ShortTwintails",
      numFilters: 0,
    },
    {
      id: 39,
      name: "Кудрявый пикси",
      img: filter,
      hair_style: "ShortCurlyPixie",
      numFilters: 0,
    },
    {
      id: 40,
      name: "Прямые",
      img: filter,
      hair_style: "LongStraight",
      numFilters: 0,
    },
    {
      id: 41,
      name: "Волнистые",
      img: filter,
      hair_style: "LongWavy",
      numFilters: 0,
    },
    {
      id: 42,
      name: "Рыбий хвост",
      img: filter,
      hair_style: "FishtailBraid",
      numFilters: 0,
    },
    {
      id: 43,
      name: "Две косы",
      img: filter,
      hair_style: "TwinBraids",
      numFilters: 0,
    },
    {
      id: 44,
      name: "Хвост",
      img: filter,
      hair_style: "Ponytail",
      numFilters: 0,
    },
    {
      id: 45,
      name: "Дреды",
      img: filter,
      hair_style: "Dreadlocks",
      numFilters: 0,
    },
    {
      id: 46,
      name: "Косички",
      img: filter,
      hair_style: "Cornrows",
      numFilters: 0,
    },
    {
      id: 47,
      name: "До плеч",
      img: filter,
      hair_style: "ShoulderLengthHair",
      numFilters: 0,
    },
    {
      id: 48,
      name: "Пышное афро",
      img: filter,
      hair_style: "LooseCurlyAfro",
      numFilters: 0,
    },
    {
      id: 49,
      name: "Длинные хвостики",
      img: filter,
      hair_style: "LongTwintails",
      numFilters: 0,
    },
    {
      id: 50,
      name: "Химе",
      img: filter,
      hair_style: "LongHimeCut",
      numFilters: 0,
    },
    {
      id: 51,
      name: "Боксы",
      img: filter,
      hair_style: "BoxBraids",
      numFilters: 0,
    },
  ],

  filter: [
    { id: 0, name: "Белый чай", img: filter, resource_type: 10001 },
    { id: 1, name: "Светлая кожа", img: filter, resource_type: 10002 },
    { id: 2, name: "Раннее лето", img: filter, resource_type: 10003 },
    { id: 3, name: "Токио", img: filter, resource_type: 10004 },
    { id: 4, name: "Признание", img: filter, resource_type: 10005 },
    { id: 5, name: "Тёплое солнце", img: filter, resource_type: 10006 },
    { id: 6, name: "Роза", img: filter, resource_type: 10007 },
    { id: 7, name: "Ясность", img: filter, resource_type: 10008 },
    { id: 8, name: "Хрустальная чистота", img: filter, resource_type: 10009 },
    { id: 9, name: "Сладкая мята", img: filter, resource_type: 10010 },
    { id: 10, name: "Базовый", img: filter, resource_type: 10011 },
    { id: 11, name: "Сердцебиение", img: filter, resource_type: 10012 },
    { id: 12, name: "Приглушённый серый", img: filter, resource_type: 10013 },
    { id: 13, name: "Вишнёвый пудинг", img: filter, resource_type: 10014 },
    { id: 14, name: "Натуральный", img: filter, resource_type: 10015 },
    { id: 15, name: "Элегантность", img: filter, resource_type: 10016 },
    { id: 16, name: "Чёрно-белый", img: filter, resource_type: 10017 },
    { id: 17, name: "Фрукты", img: filter, resource_type: 10018 },
    { id: 18, name: "Любовь", img: filter, resource_type: 10019 },
    { id: 19, name: "Зима", img: filter, resource_type: 10020 },
    { id: 20, name: "Фотография", img: filter, resource_type: 10021 },
    { id: 21, name: "Лето", img: filter, resource_type: 10022 },
    { id: 22, name: "Аромат", img: filter, resource_type: 10023 },
    { id: 23, name: "Очарование", img: filter, resource_type: 10024 },
    { id: 24, name: "Трепет", img: filter, resource_type: 10025 },
    { id: 25, name: "Пляж", img: filter, resource_type: 10026 },
    { id: 26, name: "Уличный снимок", img: filter, resource_type: 10027 },
    { id: 27, name: "Сладость", img: filter, resource_type: 10028 },
    { id: 28, name: "Первый поцелуй", img: filter, resource_type: 10029 },
    { id: 29, name: "Послеобеденное время", img: filter, resource_type: 10030 },
    { id: 30, name: "Жизненность", img: filter, resource_type: 10031 },
    { id: 31, name: "Туманность", img: filter, resource_type: 10032 },
    { id: 32, name: "Радость", img: filter, resource_type: 10033 },
    { id: 33, name: "Мода", img: filter, resource_type: 10034 },
    { id: 34, name: "Пузыри", img: filter, resource_type: 10035 },
    { id: 35, name: "Лимон", img: filter, resource_type: 10036 },
    { id: 36, name: "Сахарная вата", img: filter, resource_type: 10037 },
    { id: 37, name: "Ручей", img: filter, resource_type: 10038 },
    { id: 38, name: "Красота", img: filter, resource_type: 10039 },
    { id: 39, name: "Кофе", img: filter, resource_type: 10040 },
    { id: 40, name: "Нежный росток", img: filter, resource_type: 10041 },
    { id: 41, name: "Страсть", img: filter, resource_type: 10042 },
    { id: 42, name: "Постепенное тепло", img: filter, resource_type: 10043 },
    { id: 43, name: "Завтрак", img: filter, resource_type: 10044 },
    { id: 44, name: "Белый чай", img: filter, resource_type: 10045 },
    { id: 45, name: "Светлая", img: filter, resource_type: 10046 },
    { id: 46, name: "Святость", img: filter, resource_type: 10047 },
    { id: 47, name: "Лес", img: filter, resource_type: 10048 },
    { id: 48, name: "Сёрфинг", img: filter, resource_type: 10049 },
    { id: 49, name: "Кофе с молоком", img: filter, resource_type: 10050 },
    { id: 50, name: "Прозрачный", img: filter, resource_type: 10051 },
    { id: 51, name: "Лёгкий ветерок", img: filter, resource_type: 10052 },
    { id: 52, name: "Закат", img: filter, resource_type: 10053 },
    { id: 53, name: "Сияние воды", img: filter, resource_type: 10054 },
    { id: 54, name: "Японский стиль", img: filter, resource_type: 10055 },
    { id: 55, name: "Звёздный свет", img: filter, resource_type: 10056 },
    { id: 56, name: "Солнечный свет", img: filter, resource_type: 10057 },
    { id: 57, name: "Падающие листья", img: filter, resource_type: 10058 },
    { id: 58, name: "Жизненность", img: filter, resource_type: 10059 },
    { id: 59, name: "Милочка", img: filter, resource_type: 10060 },
    { id: 60, name: "Элегантность", img: filter, resource_type: 10061 },
    { id: 61, name: "Весна", img: filter, resource_type: 10062 },
    { id: 62, name: "Рим", img: filter, resource_type: 10063 },
    { id: 63, name: "Зелень", img: filter, resource_type: 10064 },
    { id: 64, name: "Нежный бриз", img: filter, resource_type: 10065 },
    { id: 65, name: "Тёплое сердце", img: filter, resource_type: 10066 },
    { id: 66, name: "Морская вода", img: filter, resource_type: 10067 },
    { id: 67, name: "Таинственность", img: filter, resource_type: 10068 },
    { id: 68, name: "Винтаж 1", img: filter, resource_type: 10069 },
    { id: 69, name: "Винтаж 2", img: filter, resource_type: 10070 },
    { id: 70, name: "Заснеженная вершина", img: filter, resource_type: 10071 },
    { id: 71, name: "Солнечный свет", img: filter, resource_type: 10072 },
    { id: 72, name: "Плывущие облака", img: filter, resource_type: 10073 },
    { id: 73, name: "Текущие цвета", img: filter, resource_type: 10074 },
    { id: 74, name: "Плёнка", img: filter, resource_type: 10075 },
    { id: 75, name: "Ностальгия", img: filter, resource_type: 10076 },
    { id: 76, name: "Сыр", img: filter, resource_type: 10077 },
    { id: 77, name: "Бабочка", img: filter, resource_type: 10078 },
  ],
  smile: [
    {
      id: 0,
      name: "Оригинал",
      img: filter,
      service_choice: "Original",
      numFilters: 0,
    },
    {
      id: 1,
      name: "Улыбка с ямочками",
      img: filter,
      service_choice: 10,
      numFilters: 0,
    },
    {
      id: 2,
      name: "Улыбка с ямочками",
      img: filter,
      service_choice: 11,
      numFilters: 0,
    },
    {
      id: 3,
      name: "Улыбка с ямочками",
      img: filter,
      service_choice: 12,
      numFilters: 0,
    },
    {
      id: 4,
      name: "Улыбка с ямочками",
      img: filter,
      service_choice: 13,
      numFilters: 0,
    },
    {
      id: 5,
      name: "Улыбка с ямочками",
      img: filter,
      service_choice: 14,
      numFilters: 0,
    },
    {
      id: 6,
      name: "Улыбка с ямочками",
      img: filter,
      service_choice: 15,
      numFilters: 0,
    },
    {
      id: 7,
      name: "Улыбка с ямочками",
      img: filter,
      service_choice: 16,
      numFilters: 0,
    },
    ,
    {
      id: 8,
      name: "Улыбка с ямочками",
      img: filter,
      service_choice: 100,
      numFilters: 0,
    },
  ],
  beauty: { rangeType: true, multiface: 1 },
};

export const subInstruments = {
  background: [
    { id: 0, name: "Оригинал" },
    { id: 1, name: "Фон 1" },
    { id: 2, name: "Фон 2" },
    { id: 3, name: "Фон 3" },
  ],
};
